# Generated by Django 4.0.4 on 2022-06-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maraton',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=10, null=True)),
                ('surname', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=25)),
                ('birthday', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('age', models.DateField()),
                ('gender', models.IntegerField(primary_key=True, serialize=False)),
                ('time_expected', models.FloatField()),
            ],
            options={
                'verbose_name': 'Maraton',
                'verbose_name_plural': 'Maratones',
            },
        ),
    ]
