# Generated by Django 4.0.4 on 2022-06-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=10, null=True)),
                ('surname', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=25)),
                ('birthday', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('age', models.DateField()),
                ('time_expected', models.FloatField()),
                ('number', models.FloatField()),
            ],
            options={
                'verbose_name': 'Marathon',
                'verbose_name_plural': 'Marathones',
            },
        ),
        migrations.DeleteModel(
            name='Maraton',
        ),
    ]
