# Generated by Django 4.0.4 on 2022-06-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0002_marathon_delete_maraton'),
    ]

    operations = [
        migrations.CreateModel(
            name='Five_km',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=10, null=True)),
                ('surname', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=25)),
                ('age', models.DateField()),
                ('number', models.FloatField()),
                ('custome', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': '5k',
                'verbose_name_plural': 'Cinco k',
            },
        ),
        migrations.CreateModel(
            name='Half_Marathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=10, null=True)),
                ('surname', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=25)),
                ('active', models.BooleanField(default=True)),
                ('age', models.DateField()),
                ('number', models.FloatField()),
                ('relay', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Media Maraton',
                'verbose_name_plural': 'Media Maratones',
            },
        ),
        migrations.CreateModel(
            name='Ten_km',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=10, null=True)),
                ('surname', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=25)),
                ('active', models.BooleanField(default=True)),
                ('age', models.DateField()),
                ('number', models.FloatField()),
                ('search_time', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '10k',
                'verbose_name_plural': 'Diez k',
            },
        ),
        migrations.RemoveField(
            model_name='marathon',
            name='birthday',
        ),
    ]
