# Generated by Django 4.0.4 on 2022-06-28 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0003_five_km_half_marathon_ten_km_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Five_km',
        ),
        migrations.DeleteModel(
            name='Half_Marathon',
        ),
        migrations.DeleteModel(
            name='Ten_km',
        ),
    ]
