# Generated by Django 4.0.4 on 2022-06-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('edad', models.FloatField()),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('SKU', models.CharField(max_length=30)),
                ('vivo', models.BooleanField(default=True)),
            ],
        ),
    ]
